<a href="https://colab.research.google.com/github/Saurabh2997/Python/blob/master/Numpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

Write a NumPy program to test whether none of the elements of a given array is zero.

In [18]:
a=np.array([1,2,3,45,5,6,8])
print(np.all(a))
b=np.array([0,1,2,5])
print(np.all(b))

True
False


Write a NumPy program to test whether none of the elements of a given array is zero.

In [19]:
a=np.array([1,2,3,45,5,6,8])
np.any(a)


True

Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [21]:
a=np.zeros(10)
print(a)
b=np.ones(10)
print(b)
c=np.ones(10)*5
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Write a NumPy program to create an array of the integers from 30 to70.

In [22]:
a=np.arange(30,70)
print(a)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


Write a NumPy program to create an array of all the even integers from 30 to 70

In [23]:
a=np.arange(30,70,2)
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


Write a NumPy program to create a 3x3 identity matrix.

In [25]:
a=np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Write a NumPy program to generate a random number between 0 and 1

In [29]:
a=np.random.normal(0,1,size=1)
print(a)

[0.01007414]


Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [31]:
a=np.random.standard_normal(15)
print(a)

[-1.87670541  0.54528657 -0.32235641 -0.59444143  1.58062783 -0.81311807
 -2.5832603   1.17823293 -0.53901245 -0.03003852  1.73807667 -0.46028948
  0.91880908  0.29724772  0.80671854]


Write a NumPy program to create a 3X4 array using and iterate over it.

In [32]:
a=np.random.randint(1,50,(3,4))
print(a)

[[24  1 26 17]
 [16 31  5 11]
 [23 32 37 37]]


In [48]:

a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
  print(x,end=" ")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50

In [37]:
a=np.linspace(5,50,10)
print(a)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15

In [38]:
a=np.arange(20)
print('Original array',a)
a[(a>=9)&(a<=15)]*=-1
print(a)

Original array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]


. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [40]:
a=np.random.randint(0,10,5)
print(a)

[2 9 6 4 7]


Write a NumPy program to multiply the values of two given vectors

In [41]:
a=np.arange(5)
b=np.ones(5)*2
print('array 1',a)
print('array 2',b)
c=a*b
print('array 1*2',c)

array 1 [0 1 2 3 4]
array 2 [2. 2. 2. 2. 2.]
array 1*2 [0. 2. 4. 6. 8.]


Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

In [42]:
a=np.random.randint(10,21,(3,4))
print(a)

[[14 15 17 11]
 [14 18 11 18]
 [19 19 16 10]]


Write a NumPy program to find the number of rows and columns of a given matrix.

In [53]:
a = np.random.randint(0,22,(3,4))
print(a)
print(np.shape(a))

[[18 19  2 13]
 [ 4  1  2  3]
 [ 5  8  3  3]]
(3, 4)


Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0

In [55]:
a=np.ones((10,10))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.